apiVersion: v1
kind: Pod
metadata:
  name: myanil
  #namespace: anil
  labels:
    name: myapp
spec:
  containers:
  - name: myanilpod
    image: anildevops45/minikube:2
    ports:
      - containerPort: 80
